Base station processes nearly complete
BlueJayRacing/bluejayracing pull request #11
Opened 2024-02-04 01:59 UTC by Tanner-Gladson

1. Build image, run container scripts
2. Broke into 5 processes
  3. Finished skeleton for data_logger
  4. Created pit_commands process
  5. Finished transmit_prioritizer process
  6. Finished xbee_driver process

2024-02-08 03:53 UTC, aarenclwong commented on 20xt/docker/Dockerfile_station
can copy over static files inside of the docker folder to the images instead of using printf

2024-02-08 06:29 UTC, aarenclwong requested changes
a couple things to change, refer to slack and comments

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/scripts/_station_run_container.sh
not sure this build cache is necessarily working

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/scripts/station_docker_run_prod.sh
same thing as before, can use static shell files and copy them over

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/src/baja_proto/CMakeLists.txt
add project names, package names

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/src/baja_proto/include/proto_helpers.h
are we able to use references instead of pointers and keep the pointers handled in an object or is this bad

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/src/base/CMakeLists.txt
proj name and thoughts about compiling as shared for dynamic linking

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/src/base/include/helpers/ipc_config.h
should we do defines or const values in namespace? i think defines may be faster cuz compile time resolution but not sure, should look into it.

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/src/base/include/helpers/live_comm_factory.h
namespace?

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/src/base/include/mains/receive_dispatcher.h
namespace can help resolve confusion about naming possibly

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/src/base/include/mains/transmit_prioritizer.h
namespace ^

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/src/base/src/data_logger.cpp
raii the init and spin as an object we can implement later

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/src/base/src/helpers/_ipc_config.cpp
namespace and i think we can abstract the re enqueue part of the driver to this

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/src/base/src/receive_dispatcher.cpp
raii init and spin

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/src/base/src/transmit_prioritizer.cpp
same idea as before: raii

2024-02-08 06:29 UTC, aarenclwong commented on 20xt/src/base/src/xbee_driver.cpp
we can probably use ros to enable some of this to be auto run at least on the rover side

2024-02-09 01:05 UTC, Tanner-Gladson commented on 20xt/src/baja_proto/include/proto_helpers.h
Which pointers?

2024-02-09 01:15 UTC, Tanner-Gladson commented on 20xt/src/base/include/helpers/ipc_config.h
I've learned that there is a possible performance gain, but you cannot namespace defines. There's also the added danger of no type checking for define values. In this I don't think there's a benefit since queues are open/closed infrequently. Let me check if the xbee_connection.cpp file uses any consts that might benefit

2024-02-09 01:18 UTC, Tanner-Gladson commented on 20xt/src/base/src/data_logger.cpp
> +    std::cout << "Recieved data: " << data.DebugString() << std::endl;
Bug: need to remove the LiveComm lines

2024-02-09 01:19 UTC, Tanner-Gladson commented on 20xt/src/base/src/xbee_driver.cpp
yeah this is a station-only executable

2024-02-09 01:25 UTC, Tanner-Gladson commented on 20xt/src/base/src/xbee_driver.cpp
> +const static int MAX_SEND_RETRIES = 2;
replace with define

2024-02-09 01:26 UTC, Tanner-Gladson commented on 20xt/src/base/src/helpers/_ipc_config.cpp
I'll namespace the headers. What part of the driver did you think can be abstracted?

2024-02-09 01:40 UTC, Tanner-Gladson commented
1. Remove the hardcoded serial configs from xbee_connection.cpp, change xbee_driver to pass them in
2. Change serial_configs and network_config to #defines to increase performance

2024-02-17 15:54 UTC, Tanner-Gladson commented on 20xt/scripts/_station_run_container.sh
Interesting, it seems to be working for mine now

2024-02-17 15:54 UTC, Tanner-Gladson commented on 20xt/scripts/station_docker_run_prod.sh
done

2024-02-17 15:58 UTC, Tanner-Gladson commented on 20xt/src/baja_proto/CMakeLists.txt
Added project names to all of them. Not sure how to make them packages?

2024-02-17 15:58 UTC, Tanner-Gladson commented on 20xt/src/baja_proto/include/proto_helpers.h
Resolved this

2024-02-17 15:59 UTC, Tanner-Gladson commented on 20xt/src/base/CMakeLists.txt
Project name is there. Imo it's too much work to bother with dynamic linking for now. Not sure how the xbee_digi library would behave

2024-03-09 15:32 UTC, closed without merging